# develop stage
FROM node:14-bullseye-slim as develop-stage
WORKDIR /app

ENV DOCKERIZE_VERSION v0.6.1
RUN apt-get update && apt-get install -y wget && \
    wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY ./SearchQAArbeitsrecht_o/package*.json ./
RUN npm ci
#-g

COPY ./SearchQAArbeitsrecht_o/*.json /app/
COPY ./SearchQAArbeitsrecht_o/src ./src
COPY ./SearchQAArbeitsrecht_o/e2e ./e2e

RUN chown -R 1001:0 /app && \
    chmod -R g=u /app

USER 1001

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
